# Generated by Django 4.2.6 on 2024-10-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0012_rename_codigo_recuperar_usuario_token_recuperar'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
