# Generated by Django 4.2.6 on 2024-10-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0013_venta_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='total_ganancia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
