# Generated by Django 4.2.6 on 2024-10-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0014_remove_venta_total_venta_total_ganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='total_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
