# Generated by Django 4.2.6 on 2024-10-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0015_mesa_total_ganancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='total_ganancia',
            field=models.IntegerField(default=0),
        ),
    ]
